() => ({
  path: (card) => `${card.group}/${card.name}.png`,
  list: [
    // group: 'product'
    ...[
      {
        ...{ group: 'product', name: 'g_autocredit', title: 'Автокредит' },
        ...{ stars: 2, price: 10, priceGroup: ['cheap'] },
      },
      {
        ...{ group: 'product', name: 'g_mortgage', title: 'Ипотека' },
        ...{ stars: 2, price: 10, priceGroup: ['cheap'] },
      },
      {
        ...{ group: 'product', name: 'g_deposit', title: 'Депозит' },
        ...{ stars: 1, price: 4, priceGroup: ['cheap'], depositIncome: true },
      },
      {
        ...{ group: 'product', name: 'g_credit', title: 'Кредит наличными' },
        ...{ stars: 1, price: 15, priceGroup: ['cheap'] },
      },
      {
        ...{ group: 'product', name: 'g_creditcard', title: 'Кредитная карта' },
        ...{ stars: 1, price: 20, priceGroup: ['cheap'] },
      },
      {
        ...{ group: 'product', name: 'g_bankcard', title: 'Дебетовая карта' },
        ...{ price: 1, priceGroup: ['cheap'], depositIncome: true, present: true },
      },
      { group: 'product', name: 'g_safebox', title: 'Сейфовая ячейка', price: 1, priceGroup: ['cheap'], present: true },
      { group: 'product', name: 'g_exchange', title: 'Обмен валюты', price: 2, priceGroup: ['cheap'] },
      {
        ...{ group: 'product', name: 'v_autocredit', title: 'Автокредит' },
        ...{ stars: 2, price: 12, priceGroup: ['vip'] },
      },
      {
        ...{ group: 'product', name: 'v_mortgage', title: 'Ипотека' },
        ...{ stars: 2, price: 11, priceGroup: ['vip'] },
      },
      {
        ...{ group: 'product', name: 'v_deposit', title: 'Депозит' },
        ...{ stars: 1, price: 6, priceGroup: ['vip'], depositIncome: true },
      },
      {
        ...{ group: 'product', name: 'v_credit', title: 'Кредит наличными' },
        ...{ stars: 1, price: 20, priceGroup: ['vip'] },
      },
      {
        ...{ group: 'product', name: 'v_creditcard', title: 'Кредитная карта' },
        ...{ stars: 1, price: 25, priceGroup: ['vip'] },
      },
      {
        ...{ group: 'product', name: 'v_bankcard', title: 'Дебетовая карта' },
        ...{ price: 4, priceGroup: ['vip'], depositIncome: true, present: true },
      },
      { group: 'product', name: 'v_safebox', title: 'Сейфовая ячейка', price: 1, priceGroup: ['vip'], present: true },
      { group: 'product', name: 'v_exchange', title: 'Обмен валюты', price: 2, priceGroup: ['vip'] },
      {
        ...{ group: 'product', name: 'r_autocredit', title: 'Автокредит' },
        ...{ stars: 2, price: 14, priceGroup: ['tech'] },
      },
      {
        ...{ group: 'product', name: 'r_mortgage', title: 'Ипотека' },
        ...{ stars: 2, price: 12, priceGroup: ['tech'] },
      },
      {
        ...{ group: 'product', name: 'r_deposit', title: 'Депозит' },
        ...{ stars: 1, price: 8, priceGroup: ['tech'], depositIncome: true },
      },
      {
        ...{ group: 'product', name: 'r_credit', title: 'Кредит наличными' },
        ...{ stars: 1, price: 25, priceGroup: ['tech'] },
      },
      {
        ...{ group: 'product', name: 'r_creditcard', title: 'Кредитная карта' },
        ...{ stars: 1, price: 30, priceGroup: ['tech'] },
      },
      {
        ...{ group: 'product', name: 'r_bankcard', title: 'Дебетовая карта' },
        ...{ price: 7, priceGroup: ['tech'], depositIncome: true, present: true },
      },
      { group: 'product', name: 'r_safebox', title: 'Сейфовая ячейка', price: 1, priceGroup: ['tech'], present: true },
      { group: 'product', name: 'r_exchange', title: 'Обмен валюты', price: 2, priceGroup: ['tech'] },
      {
        ...{ group: 'product', name: 'b_autocredit', title: 'Автокредит' },
        ...{ stars: 2, price: 16, priceGroup: ['speed'] },
      },
      {
        ...{ group: 'product', name: 'b_mortgage', title: 'Ипотека' },
        ...{ stars: 2, price: 13, priceGroup: ['speed'] },
      },
      {
        ...{ group: 'product', name: 'b_deposit', title: 'Депозит' },
        ...{ stars: 1, price: 10, priceGroup: ['speed'], depositIncome: true },
      },
      {
        ...{ group: 'product', name: 'b_credit', title: 'Кредит наличными' },
        ...{ stars: 1, price: 30, priceGroup: ['speed'] },
      },
      {
        ...{ group: 'product', name: 'b_creditcard', title: 'Кредитная карта' },
        ...{ stars: 1, price: 35, priceGroup: ['speed'] },
      },
      {
        ...{ group: 'product', name: 'b_bankcard', title: 'Дебетовая карта' },
        ...{ price: 10, priceGroup: ['speed'], depositIncome: true, present: true },
      },
      { group: 'product', name: 'b_safebox', title: 'Сейфовая ячейка', price: 1, priceGroup: ['speed'], present: true },
      { group: 'product', name: 'b_exchange', title: 'Обмен валюты', price: 2, priceGroup: ['speed'] },
    ],
    // group: 'service'
    ...[
      { group: 'service', name: 'mobile_bank1', title: 'Мобильный банк', priceGroup: ['tech'], present: true },
      { group: 'service', name: 'mobile_bank2', title: 'Мобильный банк', priceGroup: ['tech'], present: true },
      { group: 'service', name: 'internet_bank1', title: 'Интернет-банк', priceGroup: ['tech'], present: true },
      { group: 'service', name: 'internet_bank2', title: 'Интернет-банк', priceGroup: ['tech'], present: true },
      { group: 'service', name: 'vip1', title: 'VIP обслуживание', priceGroup: ['vip'], present: true },
      { group: 'service', name: 'vip2', title: 'VIP обслуживание', priceGroup: ['vip'], present: true },
      { group: 'service', name: 'on_record1', title: 'По записи', priceGroup: ['speed'] },
      { group: 'service', name: 'on_record2', title: 'По записи', priceGroup: ['speed'] },
      { group: 'service', name: 'quick_pass1', title: 'Без очереди', priceGroup: ['speed'] },
      { group: 'service', name: 'quick_pass2', title: 'Без очереди', priceGroup: ['speed'] },
      { group: 'service', name: 'event1', title: 'Акция', priceGroup: ['cheap'] },
      { group: 'service', name: 'event2', title: 'Акция', priceGroup: ['cheap'] },
      { group: 'service', name: 'no_commission1', title: 'Без комиссии', priceGroup: ['cheap'] },
      { group: 'service', name: 'no_commission2', title: 'Без комиссии', priceGroup: ['cheap'] },
      { group: 'service', name: 'present1', title: 'Подарок', present: true },
      { group: 'service', name: 'present2', title: 'Подарок', present: true },
      { group: 'service', name: 'present3', title: 'Подарок', present: true },
      { group: 'service', name: 'present4', title: 'Подарок', present: true },
      { group: 'service', name: 'present5', title: 'Подарок', present: true },
      { group: 'service', name: 'present6', title: 'Подарок', present: true },
      { group: 'service', name: 'cross_sale1', title: 'Кросс-продажа', crossSales: true },
      { group: 'service', name: 'cross_sale2', title: 'Кросс-продажа', crossSales: true },
      { group: 'service', name: 'cross_sale3', title: 'Кросс-продажа', crossSales: true },
      { group: 'service', name: 'cross_sale4', title: 'Кросс-продажа', crossSales: true },
      { group: 'service', name: 'cross_sale5', title: 'Кросс-продажа', crossSales: true },
      { group: 'service', name: 'cross_sale6', title: 'Кросс-продажа', crossSales: true },
      { group: 'service', name: 'credit_limit1', title: 'Увеличенный кредитный лимит', creditLimit: 50 },
      { group: 'service', name: 'credit_limit2', title: 'Увеличенный кредитный лимит', creditLimit: 50 },
      { group: 'service', name: 'credit_limit3', title: 'Увеличенный кредитный лимит', creditLimit: 50 },
      { group: 'service', name: 'credit_limit4', title: 'Увеличенный кредитный лимит', creditLimit: 50 },
      { group: 'service', name: 'credit_limit5', title: 'Увеличенный кредитный лимит', creditLimit: 50 },
      { group: 'service', name: 'credit_limit6', title: 'Увеличенный кредитный лимит', creditLimit: 50 },
    ],
    // group: 'client'
    ...[
      { group: 'client', name: 'professor', title: 'Профессор', risk: 1, money: 1000, priceGroup: ['cheap', 'vip'] },
      { group: 'client', name: 'deputy', title: 'Помощник депутата', risk: 4, money: 2000, priceGroup: ['vip'] },
      { group: 'client', name: 'writer', title: 'Писательница', risk: 3, money: 1500, priceGroup: ['vip'] },
      { group: 'client', name: 'top_manager', title: 'Топ-менеджер', risk: 1, money: 2500, priceGroup: ['vip'] },
      {
        ...{ group: 'client', name: 'business_woman', title: 'Бизнес-леди' },
        ...{ risk: 2, money: 2500, priceGroup: ['vip', 'speed'] },
      },
      { group: 'client', name: 'farmer', title: 'Фермер', risk: 4, money: 2000, priceGroup: ['cheap'] },
      { group: 'client', name: 'emigrant', title: 'Эмигрант', risk: 6, money: 500, priceGroup: ['cheap'] },
      { group: 'client', name: 'blond', title: 'Блондинка', risk: 6, money: 1500, priceGroup: ['speed'] },
      { group: 'client', name: 'student1', title: 'Студентка', risk: 6, money: 500, priceGroup: ['speed', 'tech'] },
      { group: 'client', name: 'sportsman', title: 'Спортсмен', risk: 4, money: 1000, priceGroup: ['speed', 'tech'] },
      { group: 'client', name: 'student2', title: 'Студент', risk: 6, money: 500, priceGroup: ['tech'] },
      { group: 'client', name: 'architect', title: 'Архитектор', risk: 3, money: 1500, priceGroup: ['tech'] },
      { group: 'client', name: 'blogger', title: 'Блогер', risk: 3, money: 1000, priceGroup: ['tech', 'vip'] },
      { group: 'client', name: 'traveler', title: 'Любители путешествий', risk: 5, money: 1000, priceGroup: ['tech'] },
      { group: 'client', name: 'family1', title: 'Семейная пара', risk: 2, money: 1000, priceGroup: ['cheap'] },
      { group: 'client', name: 'family2', title: 'Семейная пара', risk: 1, money: 1500, priceGroup: ['cheap'] },
      {
        ...{ group: 'client', name: 'young_family1', title: 'Молодожены' },
        ...{ risk: 4, money: 500, priceGroup: ['cheap', 'tech'] },
      },
      {
        ...{ group: 'client', name: 'young_family2', title: 'Молодожены' },
        ...{ risk: 3, money: 1000, priceGroup: ['cheap', 'tech'] },
      },
      { group: 'client', name: 'programmer', title: 'Программист', risk: 2, money: 1500, priceGroup: ['tech'] },
      { group: 'client', name: 'pensioner', title: 'Пенсионер', risk: 1, money: 500, priceGroup: ['speed'] },
      { group: 'client', name: 'entrepreneur', title: 'Предприниматель', risk: 4, money: 2000, priceGroup: ['cheap'] },
      { group: 'client', name: 'major', title: 'Мажор', risk: 6, money: 1500, priceGroup: ['speed', 'vip'] },
      {
        ...{ group: 'client', name: 'director', title: 'Директор завода' },
        ...{ risk: 1, money: 2500, priceGroup: ['cheap', 'vip'] },
      },
      {
        ...{ group: 'client', name: 'young_mom', title: 'Молодая мама' },
        ...{ risk: 2, money: 500, priceGroup: ['cheap', 'speed'] },
      },
    ],
    // group: 'feature'
    ...[
      { group: 'feature', name: 'regular_client1', title: 'Постоянный клиент', priceGroup: ['vip'] },
      { group: 'feature', name: 'regular_client2', title: 'Постоянный клиент', priceGroup: ['vip'] },
      { group: 'feature', name: 'regular_client3', title: 'Постоянный клиент', priceGroup: ['vip'] },
      { group: 'feature', name: 'regular_client4', title: 'Постоянный клиент', priceGroup: ['vip'] },
      { group: 'feature', name: 'another_city1', title: 'Живет в другом городе', priceGroup: ['tech'] },
      { group: 'feature', name: 'another_city2', title: 'Живет в другом городе', priceGroup: ['tech'] },
      { group: 'feature', name: 'another_city3', title: 'Живет в другом городе', priceGroup: ['tech'] },
      { group: 'feature', name: 'another_country', title: 'Живет за границей', priceGroup: ['tech', 'speed'] },
      { group: 'feature', name: 'urgently1', title: 'Нужно срочно', priceGroup: ['speed'] },
      { group: 'feature', name: 'urgently2', title: 'Нужно срочно', priceGroup: ['speed'] },
      { group: 'feature', name: 'urgently3', title: 'Нужно срочно', priceGroup: ['speed'] },
      { group: 'feature', name: 'from_boss', title: 'От начальства', priceGroup: ['speed', 'cheap'] },
      { group: 'feature', name: 'promotion1', title: 'По акции', priceGroup: ['cheap'] },
      { group: 'feature', name: 'promotion2', title: 'По акции', priceGroup: ['cheap'] },
      { group: 'feature', name: 'promotion3', title: 'По акции', priceGroup: ['cheap'] },
      { group: 'feature', name: 'bonus_card', title: 'От начальства', priceGroup: ['cheap', 'tech'] },
      { group: 'feature', name: 'friend1', title: 'Привел друга', reference: true },
      { group: 'feature', name: 'friend2', title: 'Привел друга', reference: true },
      { group: 'feature', name: 'present1', title: 'Пообещали подарок' },
      { group: 'feature', name: 'present2', title: 'Пообещали подарок' },
      { group: 'feature', name: 'problem1', title: 'Проблемный клиент' },
      { group: 'feature', name: 'problem2', title: 'Проблемный клиент' },
      { group: 'feature', name: 'problem3', title: 'Проблемный клиент' },
      { group: 'feature', name: 'problem4', title: 'Проблемный клиент' },
    ],
  ],
});
